### ISSUE TITLE
Variables not being recognised in Visual Studio Code

### ISSUE THREAD

**Issue by m1ssing-no** [KorigamiK/Anime-songs-downloader#1]
When I downloaded the file and I decided to run it in Visual Studio Code, lines 4 & 7 didn't let the program run in Terminal. The bold parts in the lines were underlined in red:  subprocess.check_call([**sys**.executable, "-m", "pip", "install", package]) and **import** requests  . Could you help me fix this?

**Comment by KorigamiK** [comment]
Ok, I will fix this shortly

**Comment by KorigamiK** [comment]
Meanwhile, you can just run 
pip install requests
On the terminal and it should work just fine.

**Comment by KorigamiK** [comment]
Tell me if you are able to tum it again, sorry for replying so late.

**Comment by KorigamiK** [comment]
Sorry, It was the silliest error I could imagine. You should not update the code on without checking for new dependicies. It should work now. you should also try my newer ost downloader which gets the anime in a lot better quality.
